[package]
name = "quick-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.30"
json = "0.12.4"
reqwest = "0.11.24"
tokio = { version = "1.36.0", features = ["full"] }
